# 设置安装路径
set(CMAKE_INSTALL_PREFIX ${CMAKE_SOURCE_DIR}/install)
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    install(TARGETS ${PROJECT_NAME}
        # MACOS INSTALL
        BUNDLE DESTINATION .
        # Other INSTALL
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}/Debug/${PROJECT_NAME}/lib
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}/Debug/${PROJECT_NAME}
    )
    # 删除安装目录中的所有文件
    install(CODE "message(STATUS \"Removing old installation...\")\nfile(REMOVE_RECURSE \"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/Debug/${PROJECT_NAME}\" \"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/Debug/${PROJECT_NAME}\" \"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/Debug/${PROJECT_NAME}/${PROJECT_NAME}.dll\")")
    # 复制exe到安装目录
    file(COPY "${EXECUTABLE_OUTPUT_PATH}" DESTINATION "${CMAKE_INSTALL_LIBDIR}/Debug/${PROJECT_NAME}")
    # 复制dll到安装目录
    file(COPY "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}" DESTINATION "${CMAKE_INSTALL_BINDIR}/Debug/${PROJECT_NAME}")
else()
    install(TARGETS ${PROJECT_NAME}
    # MACOS INSTALL 
    BUNDLE DESTINATION .
    # Other INSTALL
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}/Release/${PROJECT_NAME}/lib
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}/Release/${PROJECT_NAME}
    )
    # 删除安装目录中的所有文件
    install(CODE "message(STATUS \"Removing old installation...\")\nfile(REMOVE_RECURSE \"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/Release/${PROJECT_NAME}\" \"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/Release/${PROJECT_NAME}\" \"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/Release/${PROJECT_NAME}/${PROJECT_NAME}.dll\")")
    # 复制exe到安装目录
    file(COPY "${EXECUTABLE_OUTPUT_PATH}" DESTINATION "${CMAKE_INSTALL_LIBDIR}/Release/${PROJECT_NAME}")
    # 复制dll到安装目录
    file(COPY "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}" DESTINATION "${CMAKE_INSTALL_BINDIR}/Release/${PROJECT_NAME}")
endif()
